spring.data.mongodb.uri=${MONGODB_URI}
server.port=${PORT}
spring.main.allow-bean-definition-overriding=true
# Enable devtools livereload and disable caching for templates if any
spring.devtools.livereload.enabled=true
